export const avengers = ['Iron Man', 'Captain America', 'Captain Marvel', 'Thor']
export const allAvengers = [
  'Falcon',
  'Hulk',
  'Black Widow',
  'War Machine',
  'Quicksilver',
  'Hawkeye',
  'Scarlet Witch',
  'Black Panther',
  'Vision',
  'Spider-Man',
  'Ant-Man',
  'Nebula',
  'Rocket Raccoon',
  'Thanos',
  'Doctor Strange',
  'Gamora',
  'Loki',
  'Winter Soldier',
  'Nick Fury',
  'Mysterio',
  'Odin',
  'Star-Lord',
  'Ultron',
  'Valkyrie',
  'Venom',
]